apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace:  {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - name: ws
      port: 8765
      targetPort: 8765