apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: **
          imagePullPolicy: Always
          command: ["python", "-u", "-m", "**"]
          ports:
            - containerPort: 8765
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          livenessProbe:
            tcpSocket:
              port: 8765
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8765
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim
