apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:

      containers:
        - name: service-b
          image: **
          imagePullPolicy: Always
          command: [ "python", "-u", "-m", "**" ]
          ports:

            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: app-config

          env:
            - name: REDIS_HOST
              value: "service-r"
            - name: REDIS_PORT
              value: "6379"
            - name: WS_HOST
              value: "service-a"
            - name: WS_PORT
              value: "8765"

          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-claim